name: Build Windows EXE

on:
  push:
    branches: [ main ]  # or whatever your main branch is called
  workflow_dispatch:    # allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # match your local Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          #pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Build executable
        run: |
          pyinstaller --onefile main.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/Civ7Colors.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Auto Release"
          tag_name: "v1.0.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Civ7Colors.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


