name: Build and Release Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name Civ7Colors main.py

      - name: Create version tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Auto Release ${{ github.run_number }}"
          tag_name: "v1.0.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Civ7Colors.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
